language: php

sudo: false

before_script:
  - composer require --no-update "doctrine/orm":"${DOCTRINE_VERSION}"
  - composer require --no-update "phpunit/phpunit":"${PHPUNIT_VERSION}"
  - composer install

script:
  - vendor/bin/phpunit --verbose --colors --coverage-clover=coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  fast_finish: true
  allow_failures:
    - env: DOCTRINE_VERSION=2.6.x-dev PHPUNIT_VERSION=^6.0
  include:
    - php: 7.0
      env: DOCTRINE_VERSION=~2.4.0 PHPUNIT_VERSION=^5.3
    - php: 7.0
      env: DOCTRINE_VERSION=~2.5.0 PHPUNIT_VERSION=^5.3
    - php: 7.1
      env: DOCTRINE_VERSION=~2.4.0 PHPUNIT_VERSION=^6.0
    - php: 7.1
      env: DOCTRINE_VERSION=~2.5.0 PHPUNIT_VERSION=^6.0
    - php: 7.1
      env: DOCTRINE_VERSION=2.6.x-dev PHPUNIT_VERSION=^6.0
    - php: 7.2
      env: DOCTRINE_VERSION=~2.4.0 PHPUNIT_VERSION=^6.0
    - php: 7.2
      env: DOCTRINE_VERSION=~2.5.0 PHPUNIT_VERSION=^6.0
    - php: 7.2
      env: DOCTRINE_VERSION=2.6.x-dev PHPUNIT_VERSION=^6.0
